### ISSUE TITLE
Calculate speed and distance

### ISSUE THREAD

**Issue by lukasholtkamp** [lukasholtkamp/b.ob#15]
Calculate from the two speed pins the current driving speed and the traveled distance since startup.

- [x] Provide the current speed in m/s
- [x] Provide the traveled distance in a metric unit
- [x] Provide the wheel rotation speed in a metric unit
- [x] DriveDistance function. Given a distance, drive that much.
- [x] Make it work with ros2

**Comment by jkan67-de** [comment]
Completed in c++ but not through ROS

**Comment by jkan67-de** [comment]
driving distance function in test script
